/// Generates the Lonsdaleite content manifest from the mod's sources.
///
/// ```sh
/// puro dart run tool/generate_manifest.dart --mod /path/to/Lonsdaleite
/// puro dart run tool/generate_manifest.dart --mod /path/to/Lonsdaleite --check
/// puro dart run tool/generate_manifest.dart --verify-vanilla /path/to/Pumpkin/assets/items.json
/// ```
///
/// Writes `data/manifest.json` (readable) and `lib/src/manifest.g.dart` (the
/// same JSON embedded in the plugin, since a plugin cannot read files that
/// ship with it). `--check` writes nothing and fails when either differs.
library;

import 'dart:convert';
import 'dart:io';

import 'package:args/args.dart';

import 'src/build_manifest.dart';
import 'src/datapack_export.dart';
import 'src/java_text.dart';
import 'src/mod_data.dart';
import 'src/mod_source.dart';
import 'src/vanilla.dart' show Json;
import 'src/verify_vanilla.dart';

Future<int> main(List<String> arguments) async {
  final parser = ArgParser()
    ..addOption(
      'mod',
      help:
          'The mod checkout (default: \$LONSDALEITE_SRC). It needs common/, '
          'neoforge/ and shared-resources/.',
    )
    ..addOption('manifest', defaultsTo: 'data/manifest.json')
    ..addOption('embedded', defaultsTo: 'lib/src/manifest.g.dart')
    ..addOption(
      'verify-vanilla',
      help: 'Pumpkin\'s assets/items.json: checks the vanilla builder model against it.',
    )
    ..addOption(
      'datapack',
      help: 'Also write the mod\'s data/ folder as a data pack into this directory.',
    )
    ..addFlag('check', negatable: false, help: 'Fail if the generated files are stale.')
    ..addFlag('help', abbr: 'h', negatable: false);
  final ArgResults options;
  try {
    options = parser.parse(arguments);
  } on FormatException catch (e) {
    stderr.writeln('${e.message}\n\n${parser.usage}');
    return 64;
  }
  if (options.flag('help')) {
    print(parser.usage);
    return 0;
  }

  final dump = options.option('verify-vanilla');
  if (dump != null) return _verify(dump);

  final modPath = options.option('mod') ?? Platform.environment['LONSDALEITE_SRC'];
  if (modPath == null) {
    stderr.writeln('Pass --mod <checkout> or set LONSDALEITE_SRC.\n\n${parser.usage}');
    return 64;
  }
  final root = Directory(modPath);
  final Json manifest;
  final ModData data;
  try {
    final source = ModSource(root);
    data = ModData.read(Directory('${root.path}/shared-resources'));
    manifest = buildManifest(
      source: source,
      data: data,
      modInfo: readModInfo(root, source.modId),
    );
  } on JavaParseError catch (e) {
    stderr.writeln(e);
    return 1;
  }

  final pretty = '${const JsonEncoder.withIndent('  ').convert(manifest)}\n';
  final embedded = _embed(jsonEncode(manifest));
  final targets = {
    options.option('manifest')!: pretty,
    options.option('embedded')!: embedded,
  };

  if (options.flag('check')) {
    var stale = false;
    targets.forEach((path, content) {
      final file = File(path);
      if (!file.existsSync() || file.readAsStringSync() != content) {
        stderr.writeln('$path is stale.');
        stale = true;
      }
    });
    return stale ? 1 : 0;
  }

  targets.forEach((path, content) {
    File(path)
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(content);
    print('Wrote $path');
  });
  final datapack = options.option('datapack');
  if (datapack != null) {
    final count = exportDatapack(
      shared: Directory('${root.path}/shared-resources'),
      out: Directory(datapack),
      packMeta: data.packMeta,
    );
    print('Wrote $count data files to $datapack');
  }
  final items = manifest['items']! as List<Object?>;
  print('${items.length} items, 1 block.');
  return 0;
}

int _verify(String path) {
  final dump = jsonDecode(File(path).readAsStringSync()) as Json;
  final report = verifyAgainstVanilla(dump);
  print('${report.matched.length} vanilla items reproduced exactly.');
  for (final m in report.mismatches) {
    stderr.writeln('MISMATCH $m');
  }
  for (final f in report.failedChecks) {
    stderr.writeln('FAILED CHECK $f');
  }
  return report.ok ? 0 : 1;
}

String _embed(String compactJson) => '''
// GENERATED by tool/generate_manifest.dart from the Lonsdaleite mod sources.
// Do not edit; regenerate instead.

/// The content manifest (`data/manifest.json`) as compact JSON.
const lonsdaleiteManifestJson = r\'\'\'$compactJson\'\'\';
''';
