// Generates packages/pumpkin_api/lib/src/events.g.dart (the typed `Events`
// list) from the ABI that `tool/generate_bindings.sh` writes.
//
// Usage: dart run tool/generate_events.dart

import 'dart:convert';
import 'dart:io';

void main() {
  final abi =
      json.decode(
            File('packages/pumpkin_api/hook/wasm_abi.json').readAsStringSync(),
          )
          as Map<String, Object?>;
  final typeDefs = (abi['type_defs'] as List).cast<Map<String, Object?>>();

  final event = typeDefs.firstWhere(
    (t) => t['name'] == 'event' && (t['kind'] as Map).containsKey('variant'),
  );
  final cases =
      ((event['kind'] as Map)['variant'] as Map)['cases']
          as List<Object?>;

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_events.dart. Do not edit.')
    ..writeln("// ignore_for_file: type=lint")
    ..writeln()
    ..writeln("import 'bindings.g.dart';")
    ..writeln("import 'events.dart';")
    ..writeln()
    ..writeln('/// All events plugins can subscribe to with `Context.listen` and')
    ..writeln('/// `Context.intercept`.')
    ..writeln('abstract final class Events {');

  final seen = <String>{};
  for (final raw in cases) {
    final case_ = raw as Map<String, Object?>;
    final name = case_['name'] as String;
    final dataType = typeDefs[case_['type'] as int]['name'] as String;

    var field = _lowerCamel(name.endsWith('-event') ? name.substring(0, name.length - 6) : name);
    if (!seen.add(field)) field = _lowerCamel(name);

    final caseClass = 'Event${_upperCamel(name)}';
    final data = _upperCamel(dataType);
    out
      ..writeln('  /// `$name`.')
      ..writeln(
        '  static final $field = EventKind<$data>(EventType.${_lowerCamel(name)}, '
        '(event) => (event as $caseClass).value, $caseClass.new);',
      );
  }
  out.writeln('}');

  File('packages/pumpkin_api/lib/src/events.g.dart').writeAsStringSync('$out');
  stdout.writeln('Wrote ${cases.length} events.');
}

String _upperCamel(String kebab) => kebab
    .split('-')
    .map((w) => w.isEmpty ? w : '${w[0].toUpperCase()}${w.substring(1)}')
    .join();

String _lowerCamel(String kebab) {
  final upper = _upperCamel(kebab);
  return '${upper[0].toLowerCase()}${upper.substring(1)}';
}
