import 'model.dart';

ShopEntry _e(
  String item,
  int buy, {
  int? sell,
  int amount = 1,
  int stack = 64,
}) => ShopEntry(item: item, buy: buy, sell: sell, amount: amount, stack: stack);

/// The catalog written to `shop/catalog.json` on first run. Prices are for a
/// server whose players start with a few hundred coins.
ShopCatalog defaultCatalog() => ShopCatalog(
  categories: [
    ShopCategory(
      id: 'blocks',
      name: '&aBuilding blocks',
      icon: 'grass_block',
      entries: [
        _e('stone', 4),
        _e('cobblestone', 2),
        _e('dirt', 2),
        _e('grass_block', 3),
        _e('sand', 3),
        _e('gravel', 3),
        _e('oak_log', 6),
        _e('spruce_log', 6),
        _e('birch_log', 6),
        _e('oak_planks', 2),
        _e('glass', 5),
        _e('bricks', 10),
        _e('sandstone', 4),
        _e('andesite', 3),
        _e('deepslate', 4),
        _e('white_wool', 8),
        _e('terracotta', 6),
        _e('obsidian', 60),
        _e('netherrack', 2),
        _e('glowstone', 20),
        _e('quartz_block', 24),
      ],
    ),
    ShopCategory(
      id: 'tools',
      name: '&bTools and weapons',
      icon: 'iron_pickaxe',
      entries: [
        _e('iron_pickaxe', 120, stack: 1),
        _e('iron_axe', 120, stack: 1),
        _e('iron_shovel', 60, stack: 1),
        _e('iron_hoe', 80, stack: 1),
        _e('iron_sword', 100, stack: 1),
        _e('diamond_pickaxe', 600, stack: 1),
        _e('diamond_axe', 600, stack: 1),
        _e('diamond_shovel', 300, stack: 1),
        _e('diamond_sword', 450, stack: 1),
        _e('bow', 60, stack: 1),
        _e('arrow', 3),
        _e('shield', 70, stack: 1),
        _e('fishing_rod', 40, stack: 1),
        _e('shears', 50, stack: 1),
        _e('flint_and_steel', 40, stack: 1),
        _e('bucket', 45, stack: 16),
      ],
    ),
    ShopCategory(
      id: 'food',
      name: '&6Food',
      icon: 'bread',
      entries: [
        _e('bread', 6),
        _e('apple', 5),
        _e('carrot', 3),
        _e('potato', 3),
        _e('baked_potato', 5),
        _e('melon_slice', 2),
        _e('cooked_beef', 10),
        _e('cooked_porkchop', 10),
        _e('cooked_chicken', 8),
        _e('cooked_mutton', 9),
        _e('cooked_salmon', 9),
        _e('cooked_cod', 8),
        _e('golden_carrot', 18),
        _e('pumpkin_pie', 9),
        _e('cookie', 2),
        _e('golden_apple', 150),
      ],
    ),
    ShopCategory(
      id: 'redstone',
      name: '&cRedstone',
      icon: 'redstone',
      entries: [
        _e('redstone', 8),
        _e('redstone_torch', 10),
        _e('repeater', 24),
        _e('comparator', 40),
        _e('piston', 30),
        _e('sticky_piston', 45),
        _e('observer', 35),
        _e('hopper', 55),
        _e('dispenser', 40),
        _e('dropper', 35),
        _e('lever', 4),
        _e('stone_button', 4),
        _e('redstone_lamp', 30),
        _e('note_block', 20),
        _e('rail', 6),
        _e('powered_rail', 25),
        _e('slime_block', 90),
        _e('tnt', 60),
      ],
    ),
    ShopCategory(
      id: 'misc',
      name: '&dMiscellaneous',
      icon: 'ender_chest',
      entries: [
        _e('diamond', 100),
        _e('emerald', 80),
        _e('gold_ingot', 40),
        _e('iron_ingot', 20),
        _e('copper_ingot', 8),
        _e('coal', 6),
        _e('lapis_lazuli', 10),
        _e('torch', 2),
        _e('chest', 20),
        _e('crafting_table', 12),
        _e('furnace', 16),
        _e('white_bed', 40, stack: 1),
        _e('bone_meal', 5),
        _e('ender_pearl', 60, stack: 16),
        _e('experience_bottle', 45),
        _e('name_tag', 90),
        _e('lead', 35),
        _e('saddle', 250, stack: 1),
      ],
    ),
  ],
);
