// GENERATED by tool/generate_events.dart. Do not edit.
// ignore_for_file: type=lint

import 'bindings.g.dart';
import 'events.dart';

/// All events plugins can subscribe to with `Context.listen` and
/// `Context.intercept`.
abstract final class Events {
  /// `player-join-event`.
  static final playerJoin = EventKind<PlayerJoinEventData>(EventType.playerJoinEvent, (event) => (event as EventPlayerJoinEvent).value, EventPlayerJoinEvent.new);
  /// `player-leave-event`.
  static final playerLeave = EventKind<PlayerLeaveEventData>(EventType.playerLeaveEvent, (event) => (event as EventPlayerLeaveEvent).value, EventPlayerLeaveEvent.new);
  /// `player-login-event`.
  static final playerLogin = EventKind<PlayerLoginEventData>(EventType.playerLoginEvent, (event) => (event as EventPlayerLoginEvent).value, EventPlayerLoginEvent.new);
  /// `player-chat-event`.
  static final playerChat = EventKind<PlayerChatEventData>(EventType.playerChatEvent, (event) => (event as EventPlayerChatEvent).value, EventPlayerChatEvent.new);
  /// `player-command-send-event`.
  static final playerCommandSend = EventKind<PlayerCommandSendEventData>(EventType.playerCommandSendEvent, (event) => (event as EventPlayerCommandSendEvent).value, EventPlayerCommandSendEvent.new);
  /// `player-permission-check-event`.
  static final playerPermissionCheck = EventKind<PlayerPermissionCheckEventData>(EventType.playerPermissionCheckEvent, (event) => (event as EventPlayerPermissionCheckEvent).value, EventPlayerPermissionCheckEvent.new);
  /// `player-move-event`.
  static final playerMove = EventKind<PlayerMoveEventData>(EventType.playerMoveEvent, (event) => (event as EventPlayerMoveEvent).value, EventPlayerMoveEvent.new);
  /// `player-teleport-event`.
  static final playerTeleport = EventKind<PlayerTeleportEventData>(EventType.playerTeleportEvent, (event) => (event as EventPlayerTeleportEvent).value, EventPlayerTeleportEvent.new);
  /// `player-change-world-event`.
  static final playerChangeWorld = EventKind<PlayerChangeWorldEventData>(EventType.playerChangeWorldEvent, (event) => (event as EventPlayerChangeWorldEvent).value, EventPlayerChangeWorldEvent.new);
  /// `player-respawn-event`.
  static final playerRespawn = EventKind<PlayerRespawnEventData>(EventType.playerRespawnEvent, (event) => (event as EventPlayerRespawnEvent).value, EventPlayerRespawnEvent.new);
  /// `player-exp-change-event`.
  static final playerExpChange = EventKind<PlayerExpChangeEventData>(EventType.playerExpChangeEvent, (event) => (event as EventPlayerExpChangeEvent).value, EventPlayerExpChangeEvent.new);
  /// `player-item-held-event`.
  static final playerItemHeld = EventKind<PlayerItemHeldEventData>(EventType.playerItemHeldEvent, (event) => (event as EventPlayerItemHeldEvent).value, EventPlayerItemHeldEvent.new);
  /// `player-changed-main-hand-event`.
  static final playerChangedMainHand = EventKind<PlayerChangedMainHandEventData>(EventType.playerChangedMainHandEvent, (event) => (event as EventPlayerChangedMainHandEvent).value, EventPlayerChangedMainHandEvent.new);
  /// `player-gamemode-change-event`.
  static final playerGamemodeChange = EventKind<PlayerGamemodeChangeEventData>(EventType.playerGamemodeChangeEvent, (event) => (event as EventPlayerGamemodeChangeEvent).value, EventPlayerGamemodeChangeEvent.new);
  /// `player-custom-payload-event`.
  static final playerCustomPayload = EventKind<PlayerCustomPayloadEventData>(EventType.playerCustomPayloadEvent, (event) => (event as EventPlayerCustomPayloadEvent).value, EventPlayerCustomPayloadEvent.new);
  /// `player-fish-event`.
  static final playerFish = EventKind<PlayerFishEventData>(EventType.playerFishEvent, (event) => (event as EventPlayerFishEvent).value, EventPlayerFishEvent.new);
  /// `player-egg-throw-event`.
  static final playerEggThrow = EventKind<PlayerEggThrowEventData>(EventType.playerEggThrowEvent, (event) => (event as EventPlayerEggThrowEvent).value, EventPlayerEggThrowEvent.new);
  /// `player-interact-unknown-entity-event`.
  static final playerInteractUnknownEntity = EventKind<PlayerInteractUnknownEntityEventData>(EventType.playerInteractUnknownEntityEvent, (event) => (event as EventPlayerInteractUnknownEntityEvent).value, EventPlayerInteractUnknownEntityEvent.new);
  /// `player-interact-entity-event`.
  static final playerInteractEntity = EventKind<PlayerInteractEntityEventData>(EventType.playerInteractEntityEvent, (event) => (event as EventPlayerInteractEntityEvent).value, EventPlayerInteractEntityEvent.new);
  /// `player-interact-event`.
  static final playerInteract = EventKind<PlayerInteractEventData>(EventType.playerInteractEvent, (event) => (event as EventPlayerInteractEvent).value, EventPlayerInteractEvent.new);
  /// `player-toggle-sneak-event`.
  static final playerToggleSneak = EventKind<PlayerToggleSneakEventData>(EventType.playerToggleSneakEvent, (event) => (event as EventPlayerToggleSneakEvent).value, EventPlayerToggleSneakEvent.new);
  /// `player-toggle-flight-event`.
  static final playerToggleFlight = EventKind<PlayerToggleFlightEventData>(EventType.playerToggleFlightEvent, (event) => (event as EventPlayerToggleFlightEvent).value, EventPlayerToggleFlightEvent.new);
  /// `player-toggle-sprint-event`.
  static final playerToggleSprint = EventKind<PlayerToggleSprintEventData>(EventType.playerToggleSprintEvent, (event) => (event as EventPlayerToggleSprintEvent).value, EventPlayerToggleSprintEvent.new);
  /// `inventory-click-event`.
  static final inventoryClick = EventKind<InventoryClickEventData>(EventType.inventoryClickEvent, (event) => (event as EventInventoryClickEvent).value, EventInventoryClickEvent.new);
  /// `inventory-close-event`.
  static final inventoryClose = EventKind<InventoryCloseEventData>(EventType.inventoryCloseEvent, (event) => (event as EventInventoryCloseEvent).value, EventInventoryCloseEvent.new);
  /// `block-redstone-event`.
  static final blockRedstone = EventKind<BlockRedstoneEventData>(EventType.blockRedstoneEvent, (event) => (event as EventBlockRedstoneEvent).value, EventBlockRedstoneEvent.new);
  /// `block-break-event`.
  static final blockBreak = EventKind<BlockBreakEventData>(EventType.blockBreakEvent, (event) => (event as EventBlockBreakEvent).value, EventBlockBreakEvent.new);
  /// `block-burn-event`.
  static final blockBurn = EventKind<BlockBurnEventData>(EventType.blockBurnEvent, (event) => (event as EventBlockBurnEvent).value, EventBlockBurnEvent.new);
  /// `block-can-build-event`.
  static final blockCanBuild = EventKind<BlockCanBuildEventData>(EventType.blockCanBuildEvent, (event) => (event as EventBlockCanBuildEvent).value, EventBlockCanBuildEvent.new);
  /// `block-grow-event`.
  static final blockGrow = EventKind<BlockGrowEventData>(EventType.blockGrowEvent, (event) => (event as EventBlockGrowEvent).value, EventBlockGrowEvent.new);
  /// `block-place-event`.
  static final blockPlace = EventKind<BlockPlaceEventData>(EventType.blockPlaceEvent, (event) => (event as EventBlockPlaceEvent).value, EventBlockPlaceEvent.new);
  /// `dialog-click-action-event`.
  static final dialogClickAction = EventKind<DialogClickActionEventData>(EventType.dialogClickActionEvent, (event) => (event as EventDialogClickActionEvent).value, EventDialogClickActionEvent.new);
  /// `dialog-show-event`.
  static final dialogShow = EventKind<DialogShowEventData>(EventType.dialogShowEvent, (event) => (event as EventDialogShowEvent).value, EventDialogShowEvent.new);
  /// `dialog-clear-event`.
  static final dialogClear = EventKind<DialogClearEventData>(EventType.dialogClearEvent, (event) => (event as EventDialogClearEvent).value, EventDialogClearEvent.new);
  /// `bedrock-form-response-event`.
  static final bedrockFormResponse = EventKind<BedrockFormResponseEventData>(EventType.bedrockFormResponseEvent, (event) => (event as EventBedrockFormResponseEvent).value, EventBedrockFormResponseEvent.new);
  /// `server-command-event`.
  static final serverCommand = EventKind<ServerCommandEventData>(EventType.serverCommandEvent, (event) => (event as EventServerCommandEvent).value, EventServerCommandEvent.new);
  /// `server-list-ping-event`.
  static final serverListPing = EventKind<ServerListPingEventData>(EventType.serverListPingEvent, (event) => (event as EventServerListPingEvent).value, EventServerListPingEvent.new);
  /// `server-load-event`.
  static final serverLoad = EventKind<ServerLoadEventData>(EventType.serverLoadEvent, (event) => (event as EventServerLoadEvent).value, EventServerLoadEvent.new);
  /// `spawn-change-event`.
  static final spawnChange = EventKind<SpawnChangeEventData>(EventType.spawnChangeEvent, (event) => (event as EventSpawnChangeEvent).value, EventSpawnChangeEvent.new);
  /// `server-broadcast-event`.
  static final serverBroadcast = EventKind<ServerBroadcastEventData>(EventType.serverBroadcastEvent, (event) => (event as EventServerBroadcastEvent).value, EventServerBroadcastEvent.new);
  /// `server-tick-start-event`.
  static final serverTickStart = EventKind<ServerTickStartEventData>(EventType.serverTickStartEvent, (event) => (event as EventServerTickStartEvent).value, EventServerTickStartEvent.new);
  /// `server-tick-end-event`.
  static final serverTickEnd = EventKind<ServerTickEndEventData>(EventType.serverTickEndEvent, (event) => (event as EventServerTickEndEvent).value, EventServerTickEndEvent.new);
  /// `packet-received-event`.
  static final packetReceived = EventKind<PacketReceivedEventData>(EventType.packetReceivedEvent, (event) => (event as EventPacketReceivedEvent).value, EventPacketReceivedEvent.new);
  /// `packet-sent-event`.
  static final packetSent = EventKind<PacketSentEventData>(EventType.packetSentEvent, (event) => (event as EventPacketSentEvent).value, EventPacketSentEvent.new);
  /// `chunk-load-event`.
  static final chunkLoad = EventKind<ChunkLoadEventData>(EventType.chunkLoadEvent, (event) => (event as EventChunkLoadEvent).value, EventChunkLoadEvent.new);
  /// `chunk-save-event`.
  static final chunkSave = EventKind<ChunkSaveEventData>(EventType.chunkSaveEvent, (event) => (event as EventChunkSaveEvent).value, EventChunkSaveEvent.new);
  /// `chunk-send-event`.
  static final chunkSend = EventKind<ChunkSendEventData>(EventType.chunkSendEvent, (event) => (event as EventChunkSendEvent).value, EventChunkSendEvent.new);
  /// `entity-damage-event`.
  static final entityDamage = EventKind<EntityDamageEventData>(EventType.entityDamageEvent, (event) => (event as EventEntityDamageEvent).value, EventEntityDamageEvent.new);
  /// `entity-death-event`.
  static final entityDeath = EventKind<EntityDeathEventData>(EventType.entityDeathEvent, (event) => (event as EventEntityDeathEvent).value, EventEntityDeathEvent.new);
  /// `player-death-event`.
  static final playerDeath = EventKind<PlayerDeathEventData>(EventType.playerDeathEvent, (event) => (event as EventPlayerDeathEvent).value, EventPlayerDeathEvent.new);
  /// `entity-spawn-event`.
  static final entitySpawn = EventKind<EntitySpawnEventData>(EventType.entitySpawnEvent, (event) => (event as EventEntitySpawnEvent).value, EventEntitySpawnEvent.new);
  /// `entity-combust-event`.
  static final entityCombust = EventKind<EntityCombustEventData>(EventType.entityCombustEvent, (event) => (event as EventEntityCombustEvent).value, EventEntityCombustEvent.new);
  /// `entity-regain-health-event`.
  static final entityRegainHealth = EventKind<EntityRegainHealthEventData>(EventType.entityRegainHealthEvent, (event) => (event as EventEntityRegainHealthEvent).value, EventEntityRegainHealthEvent.new);
  /// `entity-air-change-event`.
  static final entityAirChange = EventKind<EntityAirChangeEventData>(EventType.entityAirChangeEvent, (event) => (event as EventEntityAirChangeEvent).value, EventEntityAirChangeEvent.new);
  /// `entity-breed-event`.
  static final entityBreed = EventKind<EntityBreedEventData>(EventType.entityBreedEvent, (event) => (event as EventEntityBreedEvent).value, EventEntityBreedEvent.new);
  /// `entity-dismount-event`.
  static final entityDismount = EventKind<EntityDismountEventData>(EventType.entityDismountEvent, (event) => (event as EventEntityDismountEvent).value, EventEntityDismountEvent.new);
  /// `entity-dye-event`.
  static final entityDye = EventKind<EntityDyeEventData>(EventType.entityDyeEvent, (event) => (event as EventEntityDyeEvent).value, EventEntityDyeEvent.new);
  /// `entity-enter-love-mode-event`.
  static final entityEnterLoveMode = EventKind<EntityEnterLoveModeEventData>(EventType.entityEnterLoveModeEvent, (event) => (event as EventEntityEnterLoveModeEvent).value, EventEntityEnterLoveModeEvent.new);
  /// `entity-explode-event`.
  static final entityExplode = EventKind<EntityExplodeEventData>(EventType.entityExplodeEvent, (event) => (event as EventEntityExplodeEvent).value, EventEntityExplodeEvent.new);
  /// `entity-mount-event`.
  static final entityMount = EventKind<EntityMountEventData>(EventType.entityMountEvent, (event) => (event as EventEntityMountEvent).value, EventEntityMountEvent.new);
  /// `entity-pickup-item-event`.
  static final entityPickupItem = EventKind<EntityPickupItemEventData>(EventType.entityPickupItemEvent, (event) => (event as EventEntityPickupItemEvent).value, EventEntityPickupItemEvent.new);
  /// `entity-portal-event`.
  static final entityPortal = EventKind<EntityPortalEventData>(EventType.entityPortalEvent, (event) => (event as EventEntityPortalEvent).value, EventEntityPortalEvent.new);
  /// `entity-resurrect-event`.
  static final entityResurrect = EventKind<EntityResurrectEventData>(EventType.entityResurrectEvent, (event) => (event as EventEntityResurrectEvent).value, EventEntityResurrectEvent.new);
  /// `entity-shoot-bow-event`.
  static final entityShootBow = EventKind<EntityShootBowEventData>(EventType.entityShootBowEvent, (event) => (event as EventEntityShootBowEvent).value, EventEntityShootBowEvent.new);
  /// `entity-tame-event`.
  static final entityTame = EventKind<EntityTameEventData>(EventType.entityTameEvent, (event) => (event as EventEntityTameEvent).value, EventEntityTameEvent.new);
  /// `entity-target-event`.
  static final entityTarget = EventKind<EntityTargetEventData>(EventType.entityTargetEvent, (event) => (event as EventEntityTargetEvent).value, EventEntityTargetEvent.new);
  /// `entity-teleport-event`.
  static final entityTeleport = EventKind<EntityTeleportEventData>(EventType.entityTeleportEvent, (event) => (event as EventEntityTeleportEvent).value, EventEntityTeleportEvent.new);
  /// `entity-toggle-glide-event`.
  static final entityToggleGlide = EventKind<EntityToggleGlideEventData>(EventType.entityToggleGlideEvent, (event) => (event as EventEntityToggleGlideEvent).value, EventEntityToggleGlideEvent.new);
  /// `entity-transform-event`.
  static final entityTransform = EventKind<EntityTransformEventData>(EventType.entityTransformEvent, (event) => (event as EventEntityTransformEvent).value, EventEntityTransformEvent.new);
  /// `player-item-consume-event`.
  static final playerItemConsume = EventKind<PlayerItemConsumeEventData>(EventType.playerItemConsumeEvent, (event) => (event as EventPlayerItemConsumeEvent).value, EventPlayerItemConsumeEvent.new);
  /// `player-item-damage-event`.
  static final playerItemDamage = EventKind<PlayerItemDamageEventData>(EventType.playerItemDamageEvent, (event) => (event as EventPlayerItemDamageEvent).value, EventPlayerItemDamageEvent.new);
  /// `player-drop-item-event`.
  static final playerDropItem = EventKind<PlayerDropItemEventData>(EventType.playerDropItemEvent, (event) => (event as EventPlayerDropItemEvent).value, EventPlayerDropItemEvent.new);
  /// `player-bed-enter-event`.
  static final playerBedEnter = EventKind<PlayerBedEnterEventData>(EventType.playerBedEnterEvent, (event) => (event as EventPlayerBedEnterEvent).value, EventPlayerBedEnterEvent.new);
  /// `player-bed-leave-event`.
  static final playerBedLeave = EventKind<PlayerBedLeaveEventData>(EventType.playerBedLeaveEvent, (event) => (event as EventPlayerBedLeaveEvent).value, EventPlayerBedLeaveEvent.new);
  /// `player-bucket-empty-event`.
  static final playerBucketEmpty = EventKind<PlayerBucketEmptyEventData>(EventType.playerBucketEmptyEvent, (event) => (event as EventPlayerBucketEmptyEvent).value, EventPlayerBucketEmptyEvent.new);
  /// `player-bucket-fill-event`.
  static final playerBucketFill = EventKind<PlayerBucketFillEventData>(EventType.playerBucketFillEvent, (event) => (event as EventPlayerBucketFillEvent).value, EventPlayerBucketFillEvent.new);
  /// `block-damage-event`.
  static final blockDamage = EventKind<BlockDamageEventData>(EventType.blockDamageEvent, (event) => (event as EventBlockDamageEvent).value, EventBlockDamageEvent.new);
  /// `block-ignite-event`.
  static final blockIgnite = EventKind<BlockIgniteEventData>(EventType.blockIgniteEvent, (event) => (event as EventBlockIgniteEvent).value, EventBlockIgniteEvent.new);
  /// `block-from-to-event`.
  static final blockFromTo = EventKind<BlockFromToEventData>(EventType.blockFromToEvent, (event) => (event as EventBlockFromToEvent).value, EventBlockFromToEvent.new);
  /// `block-form-event`.
  static final blockForm = EventKind<BlockFormEventData>(EventType.blockFormEvent, (event) => (event as EventBlockFormEvent).value, EventBlockFormEvent.new);
  /// `block-fade-event`.
  static final blockFade = EventKind<BlockFadeEventData>(EventType.blockFadeEvent, (event) => (event as EventBlockFadeEvent).value, EventBlockFadeEvent.new);
  /// `block-dispense-event`.
  static final blockDispense = EventKind<BlockDispenseEventData>(EventType.blockDispenseEvent, (event) => (event as EventBlockDispenseEvent).value, EventBlockDispenseEvent.new);
  /// `block-explode-event`.
  static final blockExplode = EventKind<BlockExplodeEventData>(EventType.blockExplodeEvent, (event) => (event as EventBlockExplodeEvent).value, EventBlockExplodeEvent.new);
  /// `block-physics-event`.
  static final blockPhysics = EventKind<BlockPhysicsEventData>(EventType.blockPhysicsEvent, (event) => (event as EventBlockPhysicsEvent).value, EventBlockPhysicsEvent.new);
  /// `block-piston-extend-event`.
  static final blockPistonExtend = EventKind<BlockPistonExtendEventData>(EventType.blockPistonExtendEvent, (event) => (event as EventBlockPistonExtendEvent).value, EventBlockPistonExtendEvent.new);
  /// `block-piston-retract-event`.
  static final blockPistonRetract = EventKind<BlockPistonRetractEventData>(EventType.blockPistonRetractEvent, (event) => (event as EventBlockPistonRetractEvent).value, EventBlockPistonRetractEvent.new);
  /// `note-play-event`.
  static final notePlay = EventKind<NotePlayEventData>(EventType.notePlayEvent, (event) => (event as EventNotePlayEvent).value, EventNotePlayEvent.new);
  /// `sign-change-event`.
  static final signChange = EventKind<SignChangeEventData>(EventType.signChangeEvent, (event) => (event as EventSignChangeEvent).value, EventSignChangeEvent.new);
  /// `sponge-absorb-event`.
  static final spongeAbsorb = EventKind<SpongeAbsorbEventData>(EventType.spongeAbsorbEvent, (event) => (event as EventSpongeAbsorbEvent).value, EventSpongeAbsorbEvent.new);
  /// `tnt-prime-event`.
  static final tntPrime = EventKind<TntPrimeEventData>(EventType.tntPrimeEvent, (event) => (event as EventTntPrimeEvent).value, EventTntPrimeEvent.new);
  /// `weather-change-event`.
  static final weatherChange = EventKind<WeatherChangeEventData>(EventType.weatherChangeEvent, (event) => (event as EventWeatherChangeEvent).value, EventWeatherChangeEvent.new);
  /// `thunder-change-event`.
  static final thunderChange = EventKind<ThunderChangeEventData>(EventType.thunderChangeEvent, (event) => (event as EventThunderChangeEvent).value, EventThunderChangeEvent.new);
  /// `world-load-event`.
  static final worldLoad = EventKind<WorldLoadEventData>(EventType.worldLoadEvent, (event) => (event as EventWorldLoadEvent).value, EventWorldLoadEvent.new);
  /// `world-unload-event`.
  static final worldUnload = EventKind<WorldUnloadEventData>(EventType.worldUnloadEvent, (event) => (event as EventWorldUnloadEvent).value, EventWorldUnloadEvent.new);
  /// `async-structure-generate-event`.
  static final asyncStructureGenerate = EventKind<AsyncStructureGenerateEventData>(EventType.asyncStructureGenerateEvent, (event) => (event as EventAsyncStructureGenerateEvent).value, EventAsyncStructureGenerateEvent.new);
  /// `async-structure-spawn-event`.
  static final asyncStructureSpawn = EventKind<AsyncStructureSpawnEventData>(EventType.asyncStructureSpawnEvent, (event) => (event as EventAsyncStructureSpawnEvent).value, EventAsyncStructureSpawnEvent.new);
  /// `chunk-populate-event`.
  static final chunkPopulate = EventKind<ChunkPopulateEventData>(EventType.chunkPopulateEvent, (event) => (event as EventChunkPopulateEvent).value, EventChunkPopulateEvent.new);
  /// `chunk-unload-event`.
  static final chunkUnload = EventKind<ChunkUnloadEventData>(EventType.chunkUnloadEvent, (event) => (event as EventChunkUnloadEvent).value, EventChunkUnloadEvent.new);
  /// `entities-load-event`.
  static final entitiesLoad = EventKind<EntitiesLoadEventData>(EventType.entitiesLoadEvent, (event) => (event as EventEntitiesLoadEvent).value, EventEntitiesLoadEvent.new);
  /// `entities-unload-event`.
  static final entitiesUnload = EventKind<EntitiesUnloadEventData>(EventType.entitiesUnloadEvent, (event) => (event as EventEntitiesUnloadEvent).value, EventEntitiesUnloadEvent.new);
  /// `generic-game-event`.
  static final genericGame = EventKind<GenericGameEventData>(EventType.genericGameEvent, (event) => (event as EventGenericGameEvent).value, EventGenericGameEvent.new);
  /// `loot-generate-event`.
  static final lootGenerate = EventKind<LootGenerateEventData>(EventType.lootGenerateEvent, (event) => (event as EventLootGenerateEvent).value, EventLootGenerateEvent.new);
  /// `portal-create-event`.
  static final portalCreate = EventKind<PortalCreateEventData>(EventType.portalCreateEvent, (event) => (event as EventPortalCreateEvent).value, EventPortalCreateEvent.new);
  /// `structure-grow-event`.
  static final structureGrow = EventKind<StructureGrowEventData>(EventType.structureGrowEvent, (event) => (event as EventStructureGrowEvent).value, EventStructureGrowEvent.new);
  /// `time-skip-event`.
  static final timeSkip = EventKind<TimeSkipEventData>(EventType.timeSkipEvent, (event) => (event as EventTimeSkipEvent).value, EventTimeSkipEvent.new);
  /// `world-init-event`.
  static final worldInit = EventKind<WorldInitEventData>(EventType.worldInitEvent, (event) => (event as EventWorldInitEvent).value, EventWorldInitEvent.new);
  /// `world-save-event`.
  static final worldSave = EventKind<WorldSaveEventData>(EventType.worldSaveEvent, (event) => (event as EventWorldSaveEvent).value, EventWorldSaveEvent.new);
  /// `inventory-open-event`.
  static final inventoryOpen = EventKind<InventoryOpenEventData>(EventType.inventoryOpenEvent, (event) => (event as EventInventoryOpenEvent).value, EventInventoryOpenEvent.new);
  /// `inventory-drag-event`.
  static final inventoryDrag = EventKind<InventoryDragEventData>(EventType.inventoryDragEvent, (event) => (event as EventInventoryDragEvent).value, EventInventoryDragEvent.new);
  /// `craft-item-event`.
  static final craftItem = EventKind<CraftItemEventData>(EventType.craftItemEvent, (event) => (event as EventCraftItemEvent).value, EventCraftItemEvent.new);
  /// `furnace-smelt-event`.
  static final furnaceSmelt = EventKind<FurnaceSmeltEventData>(EventType.furnaceSmeltEvent, (event) => (event as EventFurnaceSmeltEvent).value, EventFurnaceSmeltEvent.new);
  /// `brew-event`.
  static final brew = EventKind<BrewEventData>(EventType.brewEvent, (event) => (event as EventBrewEvent).value, EventBrewEvent.new);
  /// `brewing-stand-fuel-event`.
  static final brewingStandFuel = EventKind<BrewingStandFuelEventData>(EventType.brewingStandFuelEvent, (event) => (event as EventBrewingStandFuelEvent).value, EventBrewingStandFuelEvent.new);
  /// `furnace-burn-event`.
  static final furnaceBurn = EventKind<FurnaceBurnEventData>(EventType.furnaceBurnEvent, (event) => (event as EventFurnaceBurnEvent).value, EventFurnaceBurnEvent.new);
  /// `furnace-extract-event`.
  static final furnaceExtract = EventKind<FurnaceExtractEventData>(EventType.furnaceExtractEvent, (event) => (event as EventFurnaceExtractEvent).value, EventFurnaceExtractEvent.new);
  /// `furnace-start-smelt-event`.
  static final furnaceStartSmelt = EventKind<FurnaceStartSmeltEventData>(EventType.furnaceStartSmeltEvent, (event) => (event as EventFurnaceStartSmeltEvent).value, EventFurnaceStartSmeltEvent.new);
  /// `hopper-inventory-search-event`.
  static final hopperInventorySearch = EventKind<HopperInventorySearchEventData>(EventType.hopperInventorySearchEvent, (event) => (event as EventHopperInventorySearchEvent).value, EventHopperInventorySearchEvent.new);
  /// `inventory-creative-event`.
  static final inventoryCreative = EventKind<InventoryCreativeEventData>(EventType.inventoryCreativeEvent, (event) => (event as EventInventoryCreativeEvent).value, EventInventoryCreativeEvent.new);
  /// `inventory-interact-event`.
  static final inventoryInteract = EventKind<InventoryInteractEventData>(EventType.inventoryInteractEvent, (event) => (event as EventInventoryInteractEvent).value, EventInventoryInteractEvent.new);
  /// `inventory-move-item-event`.
  static final inventoryMoveItem = EventKind<InventoryMoveItemEventData>(EventType.inventoryMoveItemEvent, (event) => (event as EventInventoryMoveItemEvent).value, EventInventoryMoveItemEvent.new);
  /// `inventory-pickup-item-event`.
  static final inventoryPickupItem = EventKind<InventoryPickupItemEventData>(EventType.inventoryPickupItemEvent, (event) => (event as EventInventoryPickupItemEvent).value, EventInventoryPickupItemEvent.new);
  /// `prepare-anvil-event`.
  static final prepareAnvil = EventKind<PrepareAnvilEventData>(EventType.prepareAnvilEvent, (event) => (event as EventPrepareAnvilEvent).value, EventPrepareAnvilEvent.new);
  /// `prepare-grindstone-event`.
  static final prepareGrindstone = EventKind<PrepareGrindstoneEventData>(EventType.prepareGrindstoneEvent, (event) => (event as EventPrepareGrindstoneEvent).value, EventPrepareGrindstoneEvent.new);
  /// `prepare-inventory-result-event`.
  static final prepareInventoryResult = EventKind<PrepareInventoryResultEventData>(EventType.prepareInventoryResultEvent, (event) => (event as EventPrepareInventoryResultEvent).value, EventPrepareInventoryResultEvent.new);
  /// `prepare-item-craft-event`.
  static final prepareItemCraft = EventKind<PrepareItemCraftEventData>(EventType.prepareItemCraftEvent, (event) => (event as EventPrepareItemCraftEvent).value, EventPrepareItemCraftEvent.new);
  /// `prepare-smithing-event`.
  static final prepareSmithing = EventKind<PrepareSmithingEventData>(EventType.prepareSmithingEvent, (event) => (event as EventPrepareSmithingEvent).value, EventPrepareSmithingEvent.new);
  /// `smith-item-event`.
  static final smithItem = EventKind<SmithItemEventData>(EventType.smithItemEvent, (event) => (event as EventSmithItemEvent).value, EventSmithItemEvent.new);
  /// `trade-select-event`.
  static final tradeSelect = EventKind<TradeSelectEventData>(EventType.tradeSelectEvent, (event) => (event as EventTradeSelectEvent).value, EventTradeSelectEvent.new);
  /// `vehicle-block-collision-event`.
  static final vehicleBlockCollision = EventKind<VehicleBlockCollisionEventData>(EventType.vehicleBlockCollisionEvent, (event) => (event as EventVehicleBlockCollisionEvent).value, EventVehicleBlockCollisionEvent.new);
  /// `vehicle-collision-event`.
  static final vehicleCollision = EventKind<VehicleCollisionEventData>(EventType.vehicleCollisionEvent, (event) => (event as EventVehicleCollisionEvent).value, EventVehicleCollisionEvent.new);
  /// `vehicle-create-event`.
  static final vehicleCreate = EventKind<VehicleCreateEventData>(EventType.vehicleCreateEvent, (event) => (event as EventVehicleCreateEvent).value, EventVehicleCreateEvent.new);
  /// `vehicle-damage-event`.
  static final vehicleDamage = EventKind<VehicleDamageEventData>(EventType.vehicleDamageEvent, (event) => (event as EventVehicleDamageEvent).value, EventVehicleDamageEvent.new);
  /// `vehicle-destroy-event`.
  static final vehicleDestroy = EventKind<VehicleDestroyEventData>(EventType.vehicleDestroyEvent, (event) => (event as EventVehicleDestroyEvent).value, EventVehicleDestroyEvent.new);
  /// `vehicle-enter-event`.
  static final vehicleEnter = EventKind<VehicleEnterEventData>(EventType.vehicleEnterEvent, (event) => (event as EventVehicleEnterEvent).value, EventVehicleEnterEvent.new);
  /// `vehicle-entity-collision-event`.
  static final vehicleEntityCollision = EventKind<VehicleEntityCollisionEventData>(EventType.vehicleEntityCollisionEvent, (event) => (event as EventVehicleEntityCollisionEvent).value, EventVehicleEntityCollisionEvent.new);
  /// `vehicle-exit-event`.
  static final vehicleExit = EventKind<VehicleExitEventData>(EventType.vehicleExitEvent, (event) => (event as EventVehicleExitEvent).value, EventVehicleExitEvent.new);
  /// `vehicle-move-event`.
  static final vehicleMove = EventKind<VehicleMoveEventData>(EventType.vehicleMoveEvent, (event) => (event as EventVehicleMoveEvent).value, EventVehicleMoveEvent.new);
  /// `vehicle-update-event`.
  static final vehicleUpdate = EventKind<VehicleUpdateEventData>(EventType.vehicleUpdateEvent, (event) => (event as EventVehicleUpdateEvent).value, EventVehicleUpdateEvent.new);
  /// `prepare-item-enchant-event`.
  static final prepareItemEnchant = EventKind<PrepareItemEnchantEventData>(EventType.prepareItemEnchantEvent, (event) => (event as EventPrepareItemEnchantEvent).value, EventPrepareItemEnchantEvent.new);
  /// `enchant-item-event`.
  static final enchantItem = EventKind<EnchantItemEventData>(EventType.enchantItemEvent, (event) => (event as EventEnchantItemEvent).value, EventEnchantItemEvent.new);
  /// `map-initialize-event`.
  static final mapInitialize = EventKind<MapInitializeEventData>(EventType.mapInitializeEvent, (event) => (event as EventMapInitializeEvent).value, EventMapInitializeEvent.new);
  /// `hanging-break-event`.
  static final hangingBreak = EventKind<HangingBreakEventData>(EventType.hangingBreakEvent, (event) => (event as EventHangingBreakEvent).value, EventHangingBreakEvent.new);
  /// `hanging-break-by-entity-event`.
  static final hangingBreakByEntity = EventKind<HangingBreakByEntityEventData>(EventType.hangingBreakByEntityEvent, (event) => (event as EventHangingBreakByEntityEvent).value, EventHangingBreakByEntityEvent.new);
  /// `hanging-place-event`.
  static final hangingPlace = EventKind<HangingPlaceEventData>(EventType.hangingPlaceEvent, (event) => (event as EventHangingPlaceEvent).value, EventHangingPlaceEvent.new);
  /// `bell-resonate-event`.
  static final bellResonate = EventKind<BellResonateEventData>(EventType.bellResonateEvent, (event) => (event as EventBellResonateEvent).value, EventBellResonateEvent.new);
  /// `bell-ring-event`.
  static final bellRing = EventKind<BellRingEventData>(EventType.bellRingEvent, (event) => (event as EventBellRingEvent).value, EventBellRingEvent.new);
  /// `block-brush-event`.
  static final blockBrush = EventKind<BlockBrushEventData>(EventType.blockBrushEvent, (event) => (event as EventBlockBrushEvent).value, EventBlockBrushEvent.new);
  /// `block-cook-event`.
  static final blockCook = EventKind<BlockCookEventData>(EventType.blockCookEvent, (event) => (event as EventBlockCookEvent).value, EventBlockCookEvent.new);
  /// `block-damage-abort-event`.
  static final blockDamageAbort = EventKind<BlockDamageAbortEventData>(EventType.blockDamageAbortEvent, (event) => (event as EventBlockDamageAbortEvent).value, EventBlockDamageAbortEvent.new);
  /// `block-dispense-armor-event`.
  static final blockDispenseArmor = EventKind<BlockDispenseArmorEventData>(EventType.blockDispenseArmorEvent, (event) => (event as EventBlockDispenseArmorEvent).value, EventBlockDispenseArmorEvent.new);
  /// `block-dispense-loot-event`.
  static final blockDispenseLoot = EventKind<BlockDispenseLootEventData>(EventType.blockDispenseLootEvent, (event) => (event as EventBlockDispenseLootEvent).value, EventBlockDispenseLootEvent.new);
  /// `block-drop-item-event`.
  static final blockDropItem = EventKind<BlockDropItemEventData>(EventType.blockDropItemEvent, (event) => (event as EventBlockDropItemEvent).value, EventBlockDropItemEvent.new);
  /// `block-exp-event`.
  static final blockExp = EventKind<BlockExpEventData>(EventType.blockExpEvent, (event) => (event as EventBlockExpEvent).value, EventBlockExpEvent.new);
  /// `block-fertilize-event`.
  static final blockFertilize = EventKind<BlockFertilizeEventData>(EventType.blockFertilizeEvent, (event) => (event as EventBlockFertilizeEvent).value, EventBlockFertilizeEvent.new);
  /// `block-multi-place-event`.
  static final blockMultiPlace = EventKind<BlockMultiPlaceEventData>(EventType.blockMultiPlaceEvent, (event) => (event as EventBlockMultiPlaceEvent).value, EventBlockMultiPlaceEvent.new);
  /// `block-receive-game-event`.
  static final blockReceiveGame = EventKind<BlockReceiveGameEventData>(EventType.blockReceiveGameEvent, (event) => (event as EventBlockReceiveGameEvent).value, EventBlockReceiveGameEvent.new);
  /// `block-shear-entity-event`.
  static final blockShearEntity = EventKind<BlockShearEntityEventData>(EventType.blockShearEntityEvent, (event) => (event as EventBlockShearEntityEvent).value, EventBlockShearEntityEvent.new);
  /// `block-spread-event`.
  static final blockSpread = EventKind<BlockSpreadEventData>(EventType.blockSpreadEvent, (event) => (event as EventBlockSpreadEvent).value, EventBlockSpreadEvent.new);
  /// `brewing-start-event`.
  static final brewingStart = EventKind<BrewingStartEventData>(EventType.brewingStartEvent, (event) => (event as EventBrewingStartEvent).value, EventBrewingStartEvent.new);
  /// `campfire-start-event`.
  static final campfireStart = EventKind<CampfireStartEventData>(EventType.campfireStartEvent, (event) => (event as EventCampfireStartEvent).value, EventCampfireStartEvent.new);
  /// `cauldron-level-change-event`.
  static final cauldronLevelChange = EventKind<CauldronLevelChangeEventData>(EventType.cauldronLevelChangeEvent, (event) => (event as EventCauldronLevelChangeEvent).value, EventCauldronLevelChangeEvent.new);
  /// `crafter-craft-event`.
  static final crafterCraft = EventKind<CrafterCraftEventData>(EventType.crafterCraftEvent, (event) => (event as EventCrafterCraftEvent).value, EventCrafterCraftEvent.new);
  /// `entity-block-form-event`.
  static final entityBlockForm = EventKind<EntityBlockFormEventData>(EventType.entityBlockFormEvent, (event) => (event as EventEntityBlockFormEvent).value, EventEntityBlockFormEvent.new);
  /// `fluid-level-change-event`.
  static final fluidLevelChange = EventKind<FluidLevelChangeEventData>(EventType.fluidLevelChangeEvent, (event) => (event as EventFluidLevelChangeEvent).value, EventFluidLevelChangeEvent.new);
  /// `inventory-block-start-event`.
  static final inventoryBlockStart = EventKind<InventoryBlockStartEventData>(EventType.inventoryBlockStartEvent, (event) => (event as EventInventoryBlockStartEvent).value, EventInventoryBlockStartEvent.new);
  /// `leaves-decay-event`.
  static final leavesDecay = EventKind<LeavesDecayEventData>(EventType.leavesDecayEvent, (event) => (event as EventLeavesDecayEvent).value, EventLeavesDecayEvent.new);
  /// `moisture-change-event`.
  static final moistureChange = EventKind<MoistureChangeEventData>(EventType.moistureChangeEvent, (event) => (event as EventMoistureChangeEvent).value, EventMoistureChangeEvent.new);
  /// `sculk-bloom-event`.
  static final sculkBloom = EventKind<SculkBloomEventData>(EventType.sculkBloomEvent, (event) => (event as EventSculkBloomEvent).value, EventSculkBloomEvent.new);
  /// `vault-display-item-event`.
  static final vaultDisplayItem = EventKind<VaultDisplayItemEventData>(EventType.vaultDisplayItemEvent, (event) => (event as EventVaultDisplayItemEvent).value, EventVaultDisplayItemEvent.new);
  /// `creature-spawn-event`.
  static final creatureSpawn = EventKind<CreatureSpawnEventData>(EventType.creatureSpawnEvent, (event) => (event as EventCreatureSpawnEvent).value, EventCreatureSpawnEvent.new);
  /// `ender-dragon-change-phase-event`.
  static final enderDragonChangePhase = EventKind<EnderDragonChangePhaseEventData>(EventType.enderDragonChangePhaseEvent, (event) => (event as EventEnderDragonChangePhaseEvent).value, EventEnderDragonChangePhaseEvent.new);
  /// `entity-break-door-event`.
  static final entityBreakDoor = EventKind<EntityBreakDoorEventData>(EventType.entityBreakDoorEvent, (event) => (event as EventEntityBreakDoorEvent).value, EventEntityBreakDoorEvent.new);
  /// `entity-change-block-event`.
  static final entityChangeBlock = EventKind<EntityChangeBlockEventData>(EventType.entityChangeBlockEvent, (event) => (event as EventEntityChangeBlockEvent).value, EventEntityChangeBlockEvent.new);
  /// `entity-damage-by-block-event`.
  static final entityDamageByBlock = EventKind<EntityDamageByBlockEventData>(EventType.entityDamageByBlockEvent, (event) => (event as EventEntityDamageByBlockEvent).value, EventEntityDamageByBlockEvent.new);
  /// `entity-damage-by-entity-event`.
  static final entityDamageByEntity = EventKind<EntityDamageByEntityEventData>(EventType.entityDamageByEntityEvent, (event) => (event as EventEntityDamageByEntityEvent).value, EventEntityDamageByEntityEvent.new);
  /// `entity-drop-item-event`.
  static final entityDropItem = EventKind<EntityDropItemEventData>(EventType.entityDropItemEvent, (event) => (event as EventEntityDropItemEvent).value, EventEntityDropItemEvent.new);
  /// `entity-enter-block-event`.
  static final entityEnterBlock = EventKind<EntityEnterBlockEventData>(EventType.entityEnterBlockEvent, (event) => (event as EventEntityEnterBlockEvent).value, EventEntityEnterBlockEvent.new);
  /// `entity-exhaustion-event`.
  static final entityExhaustion = EventKind<EntityExhaustionEventData>(EventType.entityExhaustionEvent, (event) => (event as EventEntityExhaustionEvent).value, EventEntityExhaustionEvent.new);
  /// `entity-interact-event`.
  static final entityInteract = EventKind<EntityInteractEventData>(EventType.entityInteractEvent, (event) => (event as EventEntityInteractEvent).value, EventEntityInteractEvent.new);
  /// `entity-knockback-event`.
  static final entityKnockback = EventKind<EntityKnockbackEventData>(EventType.entityKnockbackEvent, (event) => (event as EventEntityKnockbackEvent).value, EventEntityKnockbackEvent.new);
  /// `entity-place-event`.
  static final entityPlace = EventKind<EntityPlaceEventData>(EventType.entityPlaceEvent, (event) => (event as EventEntityPlaceEvent).value, EventEntityPlaceEvent.new);
  /// `entity-pose-change-event`.
  static final entityPoseChange = EventKind<EntityPoseChangeEventData>(EventType.entityPoseChangeEvent, (event) => (event as EventEntityPoseChangeEvent).value, EventEntityPoseChangeEvent.new);
  /// `entity-potion-effect-event`.
  static final entityPotionEffect = EventKind<EntityPotionEffectEventData>(EventType.entityPotionEffectEvent, (event) => (event as EventEntityPotionEffectEvent).value, EventEntityPotionEffectEvent.new);
  /// `entity-spell-cast-event`.
  static final entitySpellCast = EventKind<EntitySpellCastEventData>(EventType.entitySpellCastEvent, (event) => (event as EventEntitySpellCastEvent).value, EventEntitySpellCastEvent.new);
  /// `entity-target-living-entity-event`.
  static final entityTargetLivingEntity = EventKind<EntityTargetLivingEntityEventData>(EventType.entityTargetLivingEntityEvent, (event) => (event as EventEntityTargetLivingEntityEvent).value, EventEntityTargetLivingEntityEvent.new);
  /// `entity-toggle-swim-event`.
  static final entityToggleSwim = EventKind<EntityToggleSwimEventData>(EventType.entityToggleSwimEvent, (event) => (event as EventEntityToggleSwimEvent).value, EventEntityToggleSwimEvent.new);
  /// `explosion-prime-event`.
  static final explosionPrime = EventKind<ExplosionPrimeEventData>(EventType.explosionPrimeEvent, (event) => (event as EventExplosionPrimeEvent).value, EventExplosionPrimeEvent.new);
  /// `firework-explode-event`.
  static final fireworkExplode = EventKind<FireworkExplodeEventData>(EventType.fireworkExplodeEvent, (event) => (event as EventFireworkExplodeEvent).value, EventFireworkExplodeEvent.new);
  /// `food-level-change-event`.
  static final foodLevelChange = EventKind<FoodLevelChangeEventData>(EventType.foodLevelChangeEvent, (event) => (event as EventFoodLevelChangeEvent).value, EventFoodLevelChangeEvent.new);
  /// `item-despawn-event`.
  static final itemDespawn = EventKind<ItemDespawnEventData>(EventType.itemDespawnEvent, (event) => (event as EventItemDespawnEvent).value, EventItemDespawnEvent.new);
  /// `item-merge-event`.
  static final itemMerge = EventKind<ItemMergeEventData>(EventType.itemMergeEvent, (event) => (event as EventItemMergeEvent).value, EventItemMergeEvent.new);
  /// `item-spawn-event`.
  static final itemSpawn = EventKind<ItemSpawnEventData>(EventType.itemSpawnEvent, (event) => (event as EventItemSpawnEvent).value, EventItemSpawnEvent.new);
  /// `piglin-barter-event`.
  static final piglinBarter = EventKind<PiglinBarterEventData>(EventType.piglinBarterEvent, (event) => (event as EventPiglinBarterEvent).value, EventPiglinBarterEvent.new);
  /// `projectile-hit-event`.
  static final projectileHit = EventKind<ProjectileHitEventData>(EventType.projectileHitEvent, (event) => (event as EventProjectileHitEvent).value, EventProjectileHitEvent.new);
  /// `projectile-launch-event`.
  static final projectileLaunch = EventKind<ProjectileLaunchEventData>(EventType.projectileLaunchEvent, (event) => (event as EventProjectileLaunchEvent).value, EventProjectileLaunchEvent.new);
  /// `sheep-dye-wool-event`.
  static final sheepDyeWool = EventKind<SheepDyeWoolEventData>(EventType.sheepDyeWoolEvent, (event) => (event as EventSheepDyeWoolEvent).value, EventSheepDyeWoolEvent.new);
  /// `sheep-regrow-wool-event`.
  static final sheepRegrowWool = EventKind<SheepRegrowWoolEventData>(EventType.sheepRegrowWoolEvent, (event) => (event as EventSheepRegrowWoolEvent).value, EventSheepRegrowWoolEvent.new);
  /// `slime-split-event`.
  static final slimeSplit = EventKind<SlimeSplitEventData>(EventType.slimeSplitEvent, (event) => (event as EventSlimeSplitEvent).value, EventSlimeSplitEvent.new);
  /// `strider-temperature-change-event`.
  static final striderTemperatureChange = EventKind<StriderTemperatureChangeEventData>(EventType.striderTemperatureChangeEvent, (event) => (event as EventStriderTemperatureChangeEvent).value, EventStriderTemperatureChangeEvent.new);
  /// `villager-acquire-trade-event`.
  static final villagerAcquireTrade = EventKind<VillagerAcquireTradeEventData>(EventType.villagerAcquireTradeEvent, (event) => (event as EventVillagerAcquireTradeEvent).value, EventVillagerAcquireTradeEvent.new);
  /// `villager-career-change-event`.
  static final villagerCareerChange = EventKind<VillagerCareerChangeEventData>(EventType.villagerCareerChangeEvent, (event) => (event as EventVillagerCareerChangeEvent).value, EventVillagerCareerChangeEvent.new);
  /// `villager-replenish-trade-event`.
  static final villagerReplenishTrade = EventKind<VillagerReplenishTradeEventData>(EventType.villagerReplenishTradeEvent, (event) => (event as EventVillagerReplenishTradeEvent).value, EventVillagerReplenishTradeEvent.new);
  /// `warden-anger-change-event`.
  static final wardenAngerChange = EventKind<WardenAngerChangeEventData>(EventType.wardenAngerChangeEvent, (event) => (event as EventWardenAngerChangeEvent).value, EventWardenAngerChangeEvent.new);
  /// `area-effect-cloud-apply-event`.
  static final areaEffectCloudApply = EventKind<AreaEffectCloudApplyEventData>(EventType.areaEffectCloudApplyEvent, (event) => (event as EventAreaEffectCloudApplyEvent).value, EventAreaEffectCloudApplyEvent.new);
  /// `arrow-body-count-change-event`.
  static final arrowBodyCountChange = EventKind<ArrowBodyCountChangeEventData>(EventType.arrowBodyCountChangeEvent, (event) => (event as EventArrowBodyCountChangeEvent).value, EventArrowBodyCountChangeEvent.new);
  /// `bat-toggle-sleep-event`.
  static final batToggleSleep = EventKind<BatToggleSleepEventData>(EventType.batToggleSleepEvent, (event) => (event as EventBatToggleSleepEvent).value, EventBatToggleSleepEvent.new);
  /// `creeper-power-event`.
  static final creeperPower = EventKind<CreeperPowerEventData>(EventType.creeperPowerEvent, (event) => (event as EventCreeperPowerEvent).value, EventCreeperPowerEvent.new);
  /// `entity-combust-by-block-event`.
  static final entityCombustByBlock = EventKind<EntityCombustByBlockEventData>(EventType.entityCombustByBlockEvent, (event) => (event as EventEntityCombustByBlockEvent).value, EventEntityCombustByBlockEvent.new);
  /// `entity-combust-by-entity-event`.
  static final entityCombustByEntity = EventKind<EntityCombustByEntityEventData>(EventType.entityCombustByEntityEvent, (event) => (event as EventEntityCombustByEntityEvent).value, EventEntityCombustByEntityEvent.new);
  /// `entity-knockback-by-entity-event`.
  static final entityKnockbackByEntity = EventKind<EntityKnockbackByEntityEventData>(EventType.entityKnockbackByEntityEvent, (event) => (event as EventEntityKnockbackByEntityEvent).value, EventEntityKnockbackByEntityEvent.new);
  /// `entity-portal-enter-event`.
  static final entityPortalEnter = EventKind<EntityPortalEnterEventData>(EventType.entityPortalEnterEvent, (event) => (event as EventEntityPortalEnterEvent).value, EventEntityPortalEnterEvent.new);
  /// `entity-portal-exit-event`.
  static final entityPortalExit = EventKind<EntityPortalExitEventData>(EventType.entityPortalExitEvent, (event) => (event as EventEntityPortalExitEvent).value, EventEntityPortalExitEvent.new);
  /// `entity-remove-event`.
  static final entityRemove = EventKind<EntityRemoveEventData>(EventType.entityRemoveEvent, (event) => (event as EventEntityRemoveEvent).value, EventEntityRemoveEvent.new);
  /// `entity-target-block-event`.
  static final entityTargetBlock = EventKind<EntityTargetBlockEventData>(EventType.entityTargetBlockEvent, (event) => (event as EventEntityTargetBlockEvent).value, EventEntityTargetBlockEvent.new);
  /// `entity-unleash-event`.
  static final entityUnleash = EventKind<EntityUnleashEventData>(EventType.entityUnleashEvent, (event) => (event as EventEntityUnleashEvent).value, EventEntityUnleashEvent.new);
  /// `exp-bottle-event`.
  static final expBottle = EventKind<ExpBottleEventData>(EventType.expBottleEvent, (event) => (event as EventExpBottleEvent).value, EventExpBottleEvent.new);
  /// `horse-jump-event`.
  static final horseJump = EventKind<HorseJumpEventData>(EventType.horseJumpEvent, (event) => (event as EventHorseJumpEvent).value, EventHorseJumpEvent.new);
  /// `lingering-potion-splash-event`.
  static final lingeringPotionSplash = EventKind<LingeringPotionSplashEventData>(EventType.lingeringPotionSplashEvent, (event) => (event as EventLingeringPotionSplashEvent).value, EventLingeringPotionSplashEvent.new);
  /// `pig-zap-event`.
  static final pigZap = EventKind<PigZapEventData>(EventType.pigZapEvent, (event) => (event as EventPigZapEvent).value, EventPigZapEvent.new);
  /// `pig-zombie-anger-event`.
  static final pigZombieAnger = EventKind<PigZombieAngerEventData>(EventType.pigZombieAngerEvent, (event) => (event as EventPigZombieAngerEvent).value, EventPigZombieAngerEvent.new);
  /// `potion-splash-event`.
  static final potionSplash = EventKind<PotionSplashEventData>(EventType.potionSplashEvent, (event) => (event as EventPotionSplashEvent).value, EventPotionSplashEvent.new);
  /// `spawner-spawn-event`.
  static final spawnerSpawn = EventKind<SpawnerSpawnEventData>(EventType.spawnerSpawnEvent, (event) => (event as EventSpawnerSpawnEvent).value, EventSpawnerSpawnEvent.new);
  /// `trial-spawner-spawn-event`.
  static final trialSpawnerSpawn = EventKind<TrialSpawnerSpawnEventData>(EventType.trialSpawnerSpawnEvent, (event) => (event as EventTrialSpawnerSpawnEvent).value, EventTrialSpawnerSpawnEvent.new);
  /// `villager-reputation-change-event`.
  static final villagerReputationChange = EventKind<VillagerReputationChangeEventData>(EventType.villagerReputationChangeEvent, (event) => (event as EventVillagerReputationChangeEvent).value, EventVillagerReputationChangeEvent.new);
  /// `async-player-chat-event`.
  static final asyncPlayerChat = EventKind<AsyncPlayerChatEventData>(EventType.asyncPlayerChatEvent, (event) => (event as EventAsyncPlayerChatEvent).value, EventAsyncPlayerChatEvent.new);
  /// `async-player-pre-login-event`.
  static final asyncPlayerPreLogin = EventKind<AsyncPlayerPreLoginEventData>(EventType.asyncPlayerPreLoginEvent, (event) => (event as EventAsyncPlayerPreLoginEvent).value, EventAsyncPlayerPreLoginEvent.new);
  /// `player-advancement-done-event`.
  static final playerAdvancementDone = EventKind<PlayerAdvancementDoneEventData>(EventType.playerAdvancementDoneEvent, (event) => (event as EventPlayerAdvancementDoneEvent).value, EventPlayerAdvancementDoneEvent.new);
  /// `player-animation-event`.
  static final playerAnimation = EventKind<PlayerAnimationEventData>(EventType.playerAnimationEvent, (event) => (event as EventPlayerAnimationEvent).value, EventPlayerAnimationEvent.new);
  /// `player-armor-stand-manipulate-event`.
  static final playerArmorStandManipulate = EventKind<PlayerArmorStandManipulateEventData>(EventType.playerArmorStandManipulateEvent, (event) => (event as EventPlayerArmorStandManipulateEvent).value, EventPlayerArmorStandManipulateEvent.new);
  /// `player-bucket-entity-event`.
  static final playerBucketEntity = EventKind<PlayerBucketEntityEventData>(EventType.playerBucketEntityEvent, (event) => (event as EventPlayerBucketEntityEvent).value, EventPlayerBucketEntityEvent.new);
  /// `player-changed-world-event`.
  static final playerChangedWorld = EventKind<PlayerChangedWorldEventData>(EventType.playerChangedWorldEvent, (event) => (event as EventPlayerChangedWorldEvent).value, EventPlayerChangedWorldEvent.new);
  /// `player-channel-event`.
  static final playerChannel = EventKind<PlayerChannelEventData>(EventType.playerChannelEvent, (event) => (event as EventPlayerChannelEvent).value, EventPlayerChannelEvent.new);
  /// `player-command-preprocess-event`.
  static final playerCommandPreprocess = EventKind<PlayerCommandPreprocessEventData>(EventType.playerCommandPreprocessEvent, (event) => (event as EventPlayerCommandPreprocessEvent).value, EventPlayerCommandPreprocessEvent.new);
  /// `player-edit-book-event`.
  static final playerEditBook = EventKind<PlayerEditBookEventData>(EventType.playerEditBookEvent, (event) => (event as EventPlayerEditBookEvent).value, EventPlayerEditBookEvent.new);
  /// `player-elytra-boost-event`.
  static final playerElytraBoost = EventKind<PlayerElytraBoostEventData>(EventType.playerElytraBoostEvent, (event) => (event as EventPlayerElytraBoostEvent).value, EventPlayerElytraBoostEvent.new);
  /// `player-exp-cooldown-change-event`.
  static final playerExpCooldownChange = EventKind<PlayerExpCooldownChangeEventData>(EventType.playerExpCooldownChangeEvent, (event) => (event as EventPlayerExpCooldownChangeEvent).value, EventPlayerExpCooldownChangeEvent.new);
  /// `player-harvest-block-event`.
  static final playerHarvestBlock = EventKind<PlayerHarvestBlockEventData>(EventType.playerHarvestBlockEvent, (event) => (event as EventPlayerHarvestBlockEvent).value, EventPlayerHarvestBlockEvent.new);
  /// `player-hide-entity-event`.
  static final playerHideEntity = EventKind<PlayerHideEntityEventData>(EventType.playerHideEntityEvent, (event) => (event as EventPlayerHideEntityEvent).value, EventPlayerHideEntityEvent.new);
  /// `player-item-break-event`.
  static final playerItemBreak = EventKind<PlayerItemBreakEventData>(EventType.playerItemBreakEvent, (event) => (event as EventPlayerItemBreakEvent).value, EventPlayerItemBreakEvent.new);
  /// `player-item-mend-event`.
  static final playerItemMend = EventKind<PlayerItemMendEventData>(EventType.playerItemMendEvent, (event) => (event as EventPlayerItemMendEvent).value, EventPlayerItemMendEvent.new);
  /// `player-kick-event`.
  static final playerKick = EventKind<PlayerKickEventData>(EventType.playerKickEvent, (event) => (event as EventPlayerKickEvent).value, EventPlayerKickEvent.new);
  /// `player-leash-entity-event`.
  static final playerLeashEntity = EventKind<PlayerLeashEntityEventData>(EventType.playerLeashEntityEvent, (event) => (event as EventPlayerLeashEntityEvent).value, EventPlayerLeashEntityEvent.new);
  /// `player-level-change-event`.
  static final playerLevelChange = EventKind<PlayerLevelChangeEventData>(EventType.playerLevelChangeEvent, (event) => (event as EventPlayerLevelChangeEvent).value, EventPlayerLevelChangeEvent.new);
  /// `player-locale-change-event`.
  static final playerLocaleChange = EventKind<PlayerLocaleChangeEventData>(EventType.playerLocaleChangeEvent, (event) => (event as EventPlayerLocaleChangeEvent).value, EventPlayerLocaleChangeEvent.new);
  /// `player-name-entity-event`.
  static final playerNameEntity = EventKind<PlayerNameEntityEventData>(EventType.playerNameEntityEvent, (event) => (event as EventPlayerNameEntityEvent).value, EventPlayerNameEntityEvent.new);
  /// `player-open-sign-event`.
  static final playerOpenSign = EventKind<PlayerOpenSignEventData>(EventType.playerOpenSignEvent, (event) => (event as EventPlayerOpenSignEvent).value, EventPlayerOpenSignEvent.new);
  /// `player-portal-event`.
  static final playerPortal = EventKind<PlayerPortalEventData>(EventType.playerPortalEvent, (event) => (event as EventPlayerPortalEvent).value, EventPlayerPortalEvent.new);
  /// `player-pre-login-event`.
  static final playerPreLogin = EventKind<PlayerPreLoginEventData>(EventType.playerPreLoginEvent, (event) => (event as EventPlayerPreLoginEvent).value, EventPlayerPreLoginEvent.new);
  /// `player-riptide-event`.
  static final playerRiptide = EventKind<PlayerRiptideEventData>(EventType.playerRiptideEvent, (event) => (event as EventPlayerRiptideEvent).value, EventPlayerRiptideEvent.new);
  /// `player-shear-entity-event`.
  static final playerShearEntity = EventKind<PlayerShearEntityEventData>(EventType.playerShearEntityEvent, (event) => (event as EventPlayerShearEntityEvent).value, EventPlayerShearEntityEvent.new);
  /// `player-show-entity-event`.
  static final playerShowEntity = EventKind<PlayerShowEntityEventData>(EventType.playerShowEntityEvent, (event) => (event as EventPlayerShowEntityEvent).value, EventPlayerShowEntityEvent.new);
  /// `player-spawn-change-event`.
  static final playerSpawnChange = EventKind<PlayerSpawnChangeEventData>(EventType.playerSpawnChangeEvent, (event) => (event as EventPlayerSpawnChangeEvent).value, EventPlayerSpawnChangeEvent.new);
  /// `player-statistic-increment-event`.
  static final playerStatisticIncrement = EventKind<PlayerStatisticIncrementEventData>(EventType.playerStatisticIncrementEvent, (event) => (event as EventPlayerStatisticIncrementEvent).value, EventPlayerStatisticIncrementEvent.new);
  /// `player-swap-hands-event`.
  static final playerSwapHands = EventKind<PlayerSwapHandsEventData>(EventType.playerSwapHandsEvent, (event) => (event as EventPlayerSwapHandsEvent).value, EventPlayerSwapHandsEvent.new);
  /// `player-take-lectern-book-event`.
  static final playerTakeLecternBook = EventKind<PlayerTakeLecternBookEventData>(EventType.playerTakeLecternBookEvent, (event) => (event as EventPlayerTakeLecternBookEvent).value, EventPlayerTakeLecternBookEvent.new);
  /// `player-unleash-entity-event`.
  static final playerUnleashEntity = EventKind<PlayerUnleashEntityEventData>(EventType.playerUnleashEntityEvent, (event) => (event as EventPlayerUnleashEntityEvent).value, EventPlayerUnleashEntityEvent.new);
  /// `player-velocity-event`.
  static final playerVelocity = EventKind<PlayerVelocityEventData>(EventType.playerVelocityEvent, (event) => (event as EventPlayerVelocityEvent).value, EventPlayerVelocityEvent.new);
  /// `player-input-event`.
  static final playerInput = EventKind<PlayerInputEventData>(EventType.playerInputEvent, (event) => (event as EventPlayerInputEvent).value, EventPlayerInputEvent.new);
  /// `player-interact-at-entity-event`.
  static final playerInteractAtEntity = EventKind<PlayerInteractAtEntityEventData>(EventType.playerInteractAtEntityEvent, (event) => (event as EventPlayerInteractAtEntityEvent).value, EventPlayerInteractAtEntityEvent.new);
  /// `player-links-send-event`.
  static final playerLinksSend = EventKind<PlayerLinksSendEventData>(EventType.playerLinksSendEvent, (event) => (event as EventPlayerLinksSendEvent).value, EventPlayerLinksSendEvent.new);
  /// `player-pickup-arrow-event`.
  static final playerPickupArrow = EventKind<PlayerPickupArrowEventData>(EventType.playerPickupArrowEvent, (event) => (event as EventPlayerPickupArrowEvent).value, EventPlayerPickupArrowEvent.new);
  /// `player-recipe-book-click-event`.
  static final playerRecipeBookClick = EventKind<PlayerRecipeBookClickEventData>(EventType.playerRecipeBookClickEvent, (event) => (event as EventPlayerRecipeBookClickEvent).value, EventPlayerRecipeBookClickEvent.new);
  /// `player-recipe-book-settings-change-event`.
  static final playerRecipeBookSettingsChange = EventKind<PlayerRecipeBookSettingsChangeEventData>(EventType.playerRecipeBookSettingsChangeEvent, (event) => (event as EventPlayerRecipeBookSettingsChangeEvent).value, EventPlayerRecipeBookSettingsChangeEvent.new);
  /// `player-recipe-discover-event`.
  static final playerRecipeDiscover = EventKind<PlayerRecipeDiscoverEventData>(EventType.playerRecipeDiscoverEvent, (event) => (event as EventPlayerRecipeDiscoverEvent).value, EventPlayerRecipeDiscoverEvent.new);
  /// `player-register-channel-event`.
  static final playerRegisterChannel = EventKind<PlayerRegisterChannelEventData>(EventType.playerRegisterChannelEvent, (event) => (event as EventPlayerRegisterChannelEvent).value, EventPlayerRegisterChannelEvent.new);
  /// `player-resource-pack-status-event`.
  static final playerResourcePackStatus = EventKind<PlayerResourcePackStatusEventData>(EventType.playerResourcePackStatusEvent, (event) => (event as EventPlayerResourcePackStatusEvent).value, EventPlayerResourcePackStatusEvent.new);
  /// `player-spawn-location-event`.
  static final playerSpawnLocation = EventKind<PlayerSpawnLocationEventData>(EventType.playerSpawnLocationEvent, (event) => (event as EventPlayerSpawnLocationEvent).value, EventPlayerSpawnLocationEvent.new);
  /// `player-unregister-channel-event`.
  static final playerUnregisterChannel = EventKind<PlayerUnregisterChannelEventData>(EventType.playerUnregisterChannelEvent, (event) => (event as EventPlayerUnregisterChannelEvent).value, EventPlayerUnregisterChannelEvent.new);
  /// `raid-finish-event`.
  static final raidFinish = EventKind<RaidFinishEventData>(EventType.raidFinishEvent, (event) => (event as EventRaidFinishEvent).value, EventRaidFinishEvent.new);
  /// `raid-spawn-wave-event`.
  static final raidSpawnWave = EventKind<RaidSpawnWaveEventData>(EventType.raidSpawnWaveEvent, (event) => (event as EventRaidSpawnWaveEvent).value, EventRaidSpawnWaveEvent.new);
  /// `raid-stop-event`.
  static final raidStop = EventKind<RaidStopEventData>(EventType.raidStopEvent, (event) => (event as EventRaidStopEvent).value, EventRaidStopEvent.new);
  /// `raid-trigger-event`.
  static final raidTrigger = EventKind<RaidTriggerEventData>(EventType.raidTriggerEvent, (event) => (event as EventRaidTriggerEvent).value, EventRaidTriggerEvent.new);
  /// `lightning-strike-event`.
  static final lightningStrike = EventKind<LightningStrikeEventData>(EventType.lightningStrikeEvent, (event) => (event as EventLightningStrikeEvent).value, EventLightningStrikeEvent.new);
}
