"""Packet ids of Minecraft Java 26.3 (protocol 777), generated from
Pumpkin crates/pumpkin-data/src/generated/packet.rs (CURRENT_MC_VERSION = V_26_3).
Only used for naming packets in logs and for the handful the client sends/answers.
"""

PROTOCOL_VERSION = 777
MC_VERSION = "26.3"

S2C_STATUS = {
    0: "status_response",
    1: "pong_response",
}

S2C_LOGIN = {
    0: "login_disconnect",
    1: "hello",
    2: "login_finished",
    3: "login_compression",
    4: "custom_query",
    5: "cookie_request",
}

S2C_CONFIG = {
    0: "cookie_request",
    1: "custom_payload",
    2: "disconnect",
    3: "finish_configuration",
    4: "keep_alive",
    5: "ping",
    6: "reset_chat",
    7: "registry_data",
    8: "resource_pack_pop",
    9: "resource_pack_push",
    10: "post_effects",
    11: "store_cookie",
    12: "transfer",
    13: "update_enabled_features",
    14: "update_tags",
    15: "select_known_packs",
    16: "custom_report_details",
    17: "server_links",
    18: "clear_dialog",
    19: "show_dialog",
    20: "code_of_conduct",
}

S2C_PLAY = {
    0: "bundle_delimiter",
    1: "add_entity",
    2: "animate",
    3: "award_stats",
    4: "block_changed_ack",
    5: "block_destruction",
    6: "block_entity_data",
    7: "block_event",
    8: "block_update",
    9: "boss_event",
    10: "change_difficulty",
    11: "chunk_batch_finished",
    12: "chunk_batch_start",
    13: "chunks_biomes",
    14: "clear_titles",
    15: "command_suggestions",
    16: "commands",
    17: "container_close",
    18: "container_set_content",
    19: "container_set_data",
    20: "container_set_slot",
    21: "cookie_request",
    22: "cooldown",
    23: "custom_chat_completions",
    24: "custom_payload",
    25: "damage_event",
    26: "debug_block_value",
    27: "debug_chunk_value",
    28: "debug_entity_value",
    29: "debug_event",
    30: "debug_sample",
    31: "delete_chat",
    32: "disconnect",
    33: "disguised_chat",
    34: "entity_event",
    35: "entity_position_sync",
    36: "explode",
    37: "add_transient_block",
    38: "forget_level_chunk",
    39: "game_event",
    40: "game_rule_values",
    41: "game_test_highlight_pos",
    42: "mount_screen_open",
    43: "hurt_animation",
    44: "initialize_border",
    45: "keep_alive",
    46: "level_chunk_with_light",
    47: "level_event",
    48: "level_particles",
    49: "light_update",
    50: "login",
    51: "low_disk_space_warning",
    52: "map_item_data",
    53: "merchant_offers",
    54: "move_entity_pos",
    55: "move_entity_pos_rot",
    56: "move_minecart_along_track",
    57: "move_entity_rot",
    58: "move_vehicle",
    59: "open_book",
    60: "open_screen",
    61: "open_sign_editor",
    62: "ping",
    63: "pong_response",
    64: "place_ghost_recipe",
    65: "player_abilities",
    66: "player_chat",
    67: "player_combat_end",
    68: "player_combat_enter",
    69: "player_combat_kill",
    70: "player_info_remove",
    71: "player_info_update",
    72: "player_look_at",
    73: "player_position",
    74: "player_rotation",
    75: "recipe_book_add",
    76: "recipe_book_remove",
    77: "recipe_book_settings",
    78: "remove_entities",
    79: "remove_mob_effect",
    80: "reset_score",
    81: "resource_pack_pop",
    82: "resource_pack_push",
    83: "post_effects",
    84: "respawn",
    85: "rotate_head",
    86: "section_blocks_update",
    87: "select_advancements_tab",
    88: "server_data",
    89: "set_action_bar_text",
    90: "set_border_center",
    91: "set_border_lerp_size",
    92: "set_border_size",
    93: "set_border_warning_delay",
    94: "set_border_warning_distance",
    95: "set_camera",
    96: "set_chunk_cache_center",
    97: "set_chunk_cache_radius",
    98: "set_cursor_item",
    99: "set_default_spawn_position",
    100: "set_display_objective",
    101: "set_entity_data",
    102: "set_entity_link",
    103: "set_entity_motion",
    104: "set_equipment",
    105: "set_experience",
    106: "set_health",
    107: "set_held_slot",
    108: "set_objective",
    109: "set_passengers",
    110: "set_player_inventory",
    111: "set_player_team",
    112: "set_score",
    113: "set_simulation_distance",
    114: "set_subtitle_text",
    115: "set_time",
    116: "set_title_text",
    117: "set_titles_animation",
    118: "sound_entity",
    119: "sound",
    120: "start_configuration",
    121: "stop_sound",
    122: "store_cookie",
    123: "swing_animation",
    124: "system_chat",
    125: "tab_list",
    126: "tag_query",
    127: "take_item_entity",
    128: "teleport_entity",
    129: "test_instance_block_status",
    130: "ticking_state",
    131: "ticking_step",
    132: "transfer",
    133: "update_advancements",
    134: "update_attributes",
    135: "update_mob_effect",
    136: "update_recipes",
    137: "update_tags",
    138: "projectile_power",
    139: "custom_report_details",
    140: "server_links",
    141: "waypoint",
    142: "clear_dialog",
    143: "show_dialog",
}

C2S_HANDSHAKE = {
    0: "intention",
}

C2S_STATUS = {
    0: "status_request",
    1: "ping_request",
}

C2S_LOGIN = {
    0: "hello",
    1: "key",
    2: "custom_query_answer",
    3: "login_acknowledged",
    4: "cookie_response",
}

C2S_CONFIG = {
    0: "client_information",
    1: "cookie_response",
    2: "custom_payload",
    3: "finish_configuration",
    4: "keep_alive",
    5: "pong",
    6: "resource_pack",
    7: "select_known_packs",
    8: "custom_click_action",
    9: "accept_code_of_conduct",
}

C2S_PLAY = {
    0: "accept_teleportation",
    1: "attack",
    2: "block_entity_tag_query",
    3: "bundle_item_selected",
    4: "change_difficulty",
    5: "change_game_mode",
    6: "chat_ack",
    7: "chat_command",
    8: "chat_command_signed",
    9: "chat",
    10: "chat_session_update",
    11: "chunk_batch_received",
    12: "client_command",
    13: "client_tick_end",
    14: "client_information",
    15: "command_suggestion",
    16: "configuration_acknowledged",
    17: "container_button_click",
    18: "container_click",
    19: "container_close",
    20: "container_slot_state_changed",
    21: "cookie_response",
    22: "custom_payload",
    23: "debug_subscription_request",
    24: "edit_book",
    25: "entity_tag_query",
    26: "interact",
    27: "jigsaw_generate",
    28: "keep_alive",
    29: "lock_difficulty",
    30: "move_player_pos",
    31: "move_player_pos_rot",
    32: "move_player_rot",
    33: "move_player_status_only",
    34: "move_vehicle",
    35: "paddle_boat",
    36: "pick_item_from_block",
    37: "pick_item_from_entity",
    38: "ping_request",
    39: "place_recipe",
    40: "player_abilities",
    41: "player_action",
    42: "player_command",
    43: "player_input",
    44: "player_loaded",
    45: "pong",
    46: "punch",
    47: "recipe_book_change_settings",
    48: "recipe_book_seen_recipe",
    49: "rename_item",
    50: "resource_pack",
    51: "seen_advancements",
    52: "select_trade",
    53: "set_beacon",
    54: "set_carried_item",
    55: "set_command_block",
    56: "set_command_minecart",
    57: "set_creative_mode_slot",
    58: "set_game_rule",
    59: "set_jigsaw_block",
    60: "set_structure_block",
    61: "set_test_block",
    62: "sign_update",
    63: "spectator_action",
    64: "teleport_to_entity",
    65: "test_instance_block_action",
    66: "use_item_on",
    67: "use_item",
    68: "custom_click_action",
}
